apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-demo
  namespace: ruoyi-demo-dev
  labels:
    app: ruoyi-demo
spec:
  selector:
    matchLabels:
      app: ruoyi-demo
  template:
    metadata:
      labels:
        app: ruoyi-demo
    spec:
      containers:
        - name: ruoyi-demo
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
          ports:
            - containerPort: 8080
          env:
            - name: host
              value: "mysql.mysql:3306"
            - name: database
              value: "ry"
            - name: username
              value: "root"
            - name: password
              valueFrom:
                secretKeyRef:
                  name: ruoyi-mysql
                  key: MYSQL_ROOT_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ruoyi-demo
  name: ruoyi-demo-svc
  namespace: ruoyi-demo-dev
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30598
  selector:
    app: ruoyi-demo
  type: NodePort